### PR TITLE
fix: prevent memory leak on macOS, closes #536

### LINKED ISSUE #536: Even if I delete it, WebView (or other?) remains.
**Describe the bug**
Let's say you have a program that creates a window to play videos.
And when I created multiple of them and then deleted some, the video in the browser that I had deleted would still be playing.

**Steps To Reproduce**
Prepare code of `wry/examples/multi_window.rs`.
Add a below snipet (YouTube embed) to [here str](https://github.com/tauri-apps/wry/blob/313eaea0ff123bddbc8b5c337ded05d464d3dfaa/examples/multi_window.rs#L52).
```html
<iframe class="background" id="background" 
src="https://www.youtube.com/embed/JUGHD_YWOe4?iv_load_policy=3&amp;loop=1&amp;playlist=JUGHD_YWOe4&amp;control=0&amp;fs=0&amp;mute=On&amp;end=111&amp;modestbranding=1&amp;start=11&amp;autoplay=1" 
frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; 
picture-in-picture" allowfullscreen="" style="width: 1191px; height: 678px;"></iframe>
```
Create about five windows every almost few seconds.
After a while, when it gets too noisy, close the window a little at a time and try to get only one.
Then it remains noisy.
So the closed window is still in motion.

**Expected behavior**
To be successfully closed.

**Screenshots**
Nothing

**Platform and Versions (please complete the following information):**
OS: macOS 12.3
Rustc: 1.59.0

**Would you assign yourself to resolve this bug?**
- [ ] Yes
- [x] No

**Additional context**
Nothing

### PR DESCRIPTION
**Pull request by keiya01**
### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [x] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

**Comment by lucasfernog** [comment]
I think you meant removing the script message handler for the IPC? https://github.com/tauri-apps/wry/blob/494a11057f9ddd2bf4bcecdc96b43ed95c5bd08e/src/webview/wkwebview/mod.rs#L307

**Comment by keiya01** [comment]
This PR is based on https://stackoverflow.com/questions/58454042/wkwebview-instances-and-memory-leak.
I'm sorry I don't know detail about this solution but we need to attach webview to scriptMessageHandler. And we can reduce memory usage when I add and remove window(webview).
But maybe this improvement is occurred only on my macOS environment, so please check it on your environment.

**Comment by keiya01** [comment]
Maybe we can also use [removeAllScriptMessageHandlers](https://developer.apple.com/documentation/webkit/wkusercontentcontroller/3585114-removeallscriptmessagehandlers?language=objc).

**Comment by lucasfernog** [comment]
Sounds like exactly what we need :)

File: src/webview/wkwebview/mod.rs [hunk 1]
```diff
@@ -476,6 +476,10 @@ r#"Object.defineProperty(window, 'ipc', {
         let ns_window = window.ns_window() as id;
         let _: () = msg_send![ns_window, setContentView: webview];
 
+        // To prevent memory leak, we need to remove webview by script message handler.
+        let interop = NSString::new("interop");
+        let _: () = msg_send![manager, addScriptMessageHandler:webview name:interop];
```
Comment (wusyong) [inline src/webview/wkwebview/mod.rs]: I feel like this should be the ipc [handler](https://github.com/tauri-apps/wry/blob/632d5439f8e1717cd86cb3d5bb49bb07a3d13545/src/webview/wkwebview/mod.rs#L302). The type of `addScriptMessageHandler` is `id<WKScriptMessageHandler>`. This is exact protocol WebViewDelegate has.

File: src/webview/wkwebview/mod.rs [hunk 2]
```diff
@@ -650,6 +654,8 @@ impl Drop for InnerWebView {
       // So we need to override the process by navigating to `about:blank`.
       self.navigate("about:blank");
 
+      let _: () = msg_send![self.manager, removeAllScriptMessageHandlers];
```
Comment (FabianLars) [inline src/webview/wkwebview/mod.rs]: This is pretty similar to what i tried, but it has the same problem. If you try to close a window the app straight up panics
> unrecognized selector sent to instance

Idk from my testing it seemed like doing it in `drop` was too late :thinking:

Comment (keiya01) [reply src/webview/wkwebview/mod.rs]: hmm, this is not occurred in my environment...
Could you show me to reproduce code?

Comment (FabianLars) [reply src/webview/wkwebview/mod.rs]: You can use this exact code (a fresh clone of your fork panics on my end too).
The easiest to use is wry's multi_window example and spawning and closing a window immediately causes a panic with a reference to this line of code.

Comment (FabianLars) [reply src/webview/wkwebview/mod.rs]: Aaahh i see why. This api was added in macos 11 and i primarily tested in 10.15

Comment (FabianLars) [reply src/webview/wkwebview/mod.rs]: Soo changing it back to `removeScriptMessageHandlerForName` doesn't panic anymore (it did in my first tests, guess i was doing something wrong.). But neither your PR nor changing it to remove `"ipc"` has an effect.

Comment (keiya01) [reply src/webview/wkwebview/mod.rs]: Oh I see.
Thank you for your description :)
I will fix it.

File: src/webview/wkwebview/mod.rs [hunk 3]
```diff
@@ -645,15 +645,8 @@ impl Drop for InnerWebView {
...
-      // WKWebview has a single WKProcessPool to manage web contents.
-      // The WKProcessPool is not reset even if WKWebview is deallocated.
-      // So we need to override the process by navigating to `about:blank`.
-      self.navigate("about:blank");
-
-      let _: Id<_> = Id::from_ptr(self.webview);
-      #[cfg(target_os = "macos")]
-      let _: Id<_> = Id::from_ptr(self.ns_window);
-      let _: Id<_> = Id::from_ptr(self.manager);
+      let _: Id<_> = Id::from_retained_ptr(self.webview);
```
Comment (keiya01) [inline src/webview/wkwebview/mod.rs:648]: I found the `Id::from_ptr` is not working well, so id object is not dropped.
I fixed these code to use `Id::from_retained_ptr` with reference to [rust-objc-id example](https://github.com/SSheldon/rust-objc-id).
If we use `Id::from_retained_ptr`, navigation to `about:blank` is not needed :)

**Review by keiya01 — COMMENTED** [review]
I changed all of commit because I found new solution 🙇

File: src/webview/wkwebview/mod.rs [hunk 4]
```diff
@@ -645,15 +645,8 @@ impl Drop for InnerWebView {
...
       }
 
-      // WKWebview has a single WKProcessPool to manage web contents.
-      // The WKProcessPool is not reset even if WKWebview is deallocated.
-      // So we need to override the process by navigating to `about:blank`.
-      self.navigate("about:blank");
-
-      let _: Id<_> = Id::from_ptr(self.webview);
-      #[cfg(target_os = "macos")]
-      let _: Id<_> = Id::from_ptr(self.ns_window);
```
Comment (keiya01) [inline src/webview/wkwebview/mod.rs:655]: I think ns_window is dropped in tao layer, so we don't need to drop it.

Comment (wusyong) [reply src/webview/wkwebview/mod.rs:655]: We control its drop here iirc. Other `Rc<Window>`s are held by all hander/callbacks which we just free above. cc @lucasfernog

File: src/webview/wkwebview/mod.rs (hunk 3 above)
Comment (FabianLars) [reply src/webview/wkwebview/mod.rs:648]: Yep, tested it and it indeed cleans up the process we were talking about correctly! nice :partying_face: 

What it still doesn''t cleanup is the Networking process, but since it does the same on Linux it looks like a webkit problem :thinking:

File: src/webview/wkwebview/mod.rs (hunk 4 above)
Comment (lucasfernog) [reply src/webview/wkwebview/mod.rs:655]: tauri doesn't hold the rc IIRC btw, do we need to do something?

File: src/webview/wkwebview/mod.rs (hunk 3 above)
Comment (keiya01) [reply src/webview/wkwebview/mod.rs:648]: I think network connection is closed but network memory is still remained. I think this is because networking process is single process, networking memory is shared between multiple webview 👀

File: src/webview/wkwebview/mod.rs (hunk 4 above)
Comment (wusyong) [reply src/webview/wkwebview/mod.rs:655]: No, I just think we still need to convert `self.ns_window` here IMHO.
`WebView` should own the `Window` and also release it when it's dropped.

File: src/webview/wkwebview/mod.rs (hunk 3 above)
Comment (keiya01) [reply src/webview/wkwebview/mod.rs:648]: > This process is responsible for handling network requests as well as storage management. All WebContent processes in a single session (default vs. private browsing) share a single networking session in the networking process.
> https://github.com/WebKit/WebKit/blob/main/Introduction.md

This is webkit description.
I think we can [remove cache](https://developer.apple.com/documentation/webkit/wkwebsitedatastore/1532938-removedataoftypes?language=objc) but all of webview cache will be removed. It will bring to bad page loading performance.

Comment (keiya01) [reply src/webview/wkwebview/mod.rs:648]: I will try to use [this gist](https://gist.github.com/dakeshi/6915b6681cbc29327dcc9b27cef263b8) to remove cache in another PR.

File: src/webview/wkwebview/mod.rs (hunk 4 above)
Comment (wusyong) [reply src/webview/wkwebview/mod.rs:655]: Just tested with removing this line and it seems fine. But I remembered we added these because of weird behavior in some combination when closing windows. Maybe take an eye on Tauri after this PR.

**Review by wusyong — DISMISSED** [review]

**Review by wusyong — APPROVED** [review]
@keiya01 LGTM. Do you want to merge this now?
I suppose networking process will be another PR right? Could you choose an issue and make it the main tracking issue?
Also you can just add a branch in this repo next time.

**Comment by keiya01** [comment]
Yes, I want to merge this PR now.
I will try to resolve https://github.com/tauri-apps/wry/issues/590 in another PR.
