### PR TITLE
fix(windows): fix init scripts running twicec

### LINKED ISSUE #2051: [bug] Click event is triggered twice
### Describe the bug

I followed the steps in the link below. I didn't any change the created files at all.

https://v2.tauri.app/start/create-project/

After the "npm run tauri dev" command the application worked. I clicked on the Tauri icon.  Tauri link opens two web pages.

The same problem occurs in the release exe created after the "npm run tauri build -release" command.

### Reproduction

Follow the steps in the link on Windows.
https://v2.tauri.app/start/create-project/

### Expected behavior

https://tauri.app/ should only be opened once

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 x86_64 (X64)
    ✔ WebView2: 130.0.2849.80
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.82.0 (f6e511eec 2024-10-15)
    ✔ cargo: 1.82.0 (8f40fc59f 2024-08-21)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.13.1
    - npm: 10.5.2

[-] Packages
    - tauri 🦀: 2.1.1
    - tauri-build 🦀: 2.0.3
    - wry 🦀: 0.47.0
    - tao 🦀: 0.30.8
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli : 2.1.0

[-] Plugins
    - tauri-plugin-shell 🦀: 2.0.2
    - @tauri-apps/plugin-shell : not installed!

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../src
```

### Stack trace

_No response_

### Additional context

Windows 11 Home 23H2

### PR DESCRIPTION
**Pull request by amrbashir**
closes tauri-apps/plugins-workspace#2051

### CODE REVIEW

**Review by pewsheen — APPROVED** [review]

File: src/webview2/mod.rs [hunk 1]
```diff
@@ -592,12 +596,27 @@ impl InnerWebView {
...
+        };
+
+        for (script, _) in scripts.iter().filter(|(_, for_main)| *for_main) {
+          Self::execute_script(&webview, script.clone(), |_| ())?;
+        }
+
+        Ok(())
+      })),
+      token,
+    )?;
```
Comment (Legend-Master) [inline src/webview2/mod.rs:614]: This looks fine but actually it sometimes injects the script at the wrong timing, for example, currently Tauri's helloworld example will throw an error saying `window.__TAURI__` is `undefined` but works if you reload the page or use `AddScriptToExecuteOnDocumentCreated`

@amrbashir I'm not sure if we want to keep this or just don't support injecting to main page only on Windows

Comment (amrbashir) [reply src/webview2/mod.rs:614]: I guess we should revert? I mean we always injected into all frames, so I don't think it should be harmful, or do we still need this @tweidinger

Comment (tweidinger) [reply src/webview2/mod.rs:614]: We moved to selective injection due to security issues like https://github.com/tauri-apps/tauri/security/advisories/GHSA-57fm-592m-34r7 - windows was always a bit of a special case since it allows injection into same origin but afaik we did not want this Auto injection behavior.
