### PR TITLE
fix(windows): set WebView2 `AllowExternalDrop` to false

### LINKED ISSUE #11274: [bug] DragDropEvents don't fire when dragging files from "Recent files" view in Windows
### Describe the bug

When you open a new file explorer in Windows 11, it opens by default on your "Home" view (which is *not* your home folder, it just contains some rapid access links to stuff you use often or you used last). 

Tauri file drag and drop events don't seem to fire when you drag a file from one of those lists. (I've just hit my head against the wall for a whole day not understanding why my file drag events don't work until I've noticed that I was dragging my test files from the "Recent files" list in Windows and that "regular files" actually worked). Even setting `dragDropEnabled` to `false` doesn't seem to work (I was trying this way to handle the drag events in HTML land, fileover events fire, but drop events don't).

I'm not 100% sure this is directly caused by tauri or somewhere upstream, but for sure people running into this problem while using tauri will look for help here. 

### Reproduction

0. Have a Windows 11 computer
1. Create a new tauri app (Typescript + Vue in my case)
2. App.vue:
```vue
<script setup lang="ts">
import { UnlistenFn } from '@tauri-apps/api/event';
import { getCurrentWebviewWindow } from '@tauri-apps/api/webviewWindow';
import { onBeforeUnmount } from 'vue';

let unlisten: UnlistenFn;

getCurrentWebviewWindow()
  .onDragDropEvent(event => console.log('onDragDropevent', event))
  .then(ul => unlisten = ul);

onBeforeUnmount(() => unlisten?.());
</script>

<template>
  <div>
    Drag files here
  </div>
</template>
```
3. Compile & Run the app
4. Open dev tools and verify:
    - Regular files work
    - Shortcuts to files work
    - Files dragged from the "Recent files" list don't work (no console message & droppping them opens a new Edge window showing or downloading them)

### Expected behavior

I kind of expect tauri to handle this situation (if possible) since for me it's the abstraction layer between the app and the OS. Or at least it should be documented somewhere that this can't be handled. 

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 x86_64 (X64)
    ✔ WebView2: 129.0.2792.79
    ✔ MSVC:
        - Visual Studio Build Tools 2019
        - Visual Studio Build Tools 2022
        - Visual Studio Community 2022
    ✔ rustc: 1.81.0 (eeb90cda1 2024-09-04)
    ✔ cargo: 1.81.0 (2dbb1af80 2024-08-20)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.18.0
    - pnpm: 9.12.0
    - npm: 10.9.0

[-] Packages
    - tauri 🦀: 2.0.1
    - tauri-build 🦀: 2.0.1
    - wry 🦀: 0.44.1
    - tao 🦀: 0.30.3
    - @tauri-apps/api : 2.0.2
    - @tauri-apps/cli : 2.0.2

[-] Plugins
    - tauri-plugin-global-shortcut 🦀: 2.0.1
    - @tauri-apps/plugin-global-shortcut : 2.0.0
    - tauri-plugin-store 🦀: 2.0.1
    - @tauri-apps/plugin-store : 2.0.0
    - tauri-plugin-single-instance 🦀: 2.0.1
    - @tauri-apps/plugin-single-instance : not installed!
    - tauri-plugin-fs 🦀: 2.0.1
    - @tauri-apps/plugin-fs : not installed!
    - tauri-plugin-shell 🦀: 2.0.1
    - @tauri-apps/plugin-shell : 2.0.0
    - tauri-plugin-http 🦀: 2.0.1
    - @tauri-apps/plugin-http : 2.0.0

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
```

### Stack trace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by amrbashir**
closes tauri-apps/tauri#11274

### CODE REVIEW

File: src/webview2/mod.rs [hunk 1]
```diff
@@ -646,6 +654,27 @@ impl InnerWebView {
       )?;
     }
 
+    webview.add_NewWindowRequested(
```
Comment (FabianLars) [inline src/webview2/mod.rs]: This is the event I wanted to abuse to make html drag and drop and our file drop work at the same time but iirc it requires the dev to not use event.preventDefault() in the frontend so never really investigated much further.

Comment (FabianLars) [reply src/webview2/mod.rs]: btw, did you commit this intentionally?

Comment (amrbashir) [reply src/webview2/mod.rs]: Lol, nah, will remove that

**Review by FabianLars — APPROVED** [review]
