### PR TITLE
fix(windows): multiple custom protocols, closes #323

### LINKED ISSUE #323: All custom protocol handlers are called on Windows
I believe the [`add_web_resource_requested`](https://github.com/tauri-apps/wry/blob/070f332b65a0859437b372c7e0970e4837efb38e/src/webview/webview2/win32/mod.rs#L145) should only be called once and the protocol name needs to be parsed from the URL, calling the proper protocol handler. Currently all handlers are called.

### PR DESCRIPTION
**Pull request by lucasfernog**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes. Issue #___
- [ ] No

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by lucasfernog** [comment]
Also fixes https://github.com/tauri-apps/tauri/issues/2124

**Comment by lucasfernog** [comment]
The issue is that all handlers were called on a specific protocol navigation, so one of them returned 404 and caused issues depending on the call order.

**Review by lemarier — APPROVED** [review]

File: src/webview/webview2/win32/mod.rs [hunk 1]
```diff
@@ -132,25 +132,34 @@ impl InnerWebView {
...
-              &format!("{}://", name),
-            );
-
-            match function(&window_, path) {
+            let path = uri
+              .replace("https://custom.protocol.", "")
+              .replacen("_", "://", 1);
+            let scheme = path.split("://").next().unwrap();
+
+            match (custom_protocols
```
Comment (wusyong) [inline src/webview/webview2/win32/mod.rs:157]: Could it just use the function that is already retrieved by L136?

**Review by wusyong — APPROVED** [review]
