### PR TITLE
fix(macOS): enable tab navigation on all elements, fixes #406

### LINKED ISSUE #406: Tab navigation not working in MacOS
**Describe the bug**
When navigating through the TAB button in a form, some elements are skipped:
- input radio
- input checkbox
- button

**Steps To Reproduce**
Clone the `snapshot/tabbing-behavior` branch from [repo](https://github.com/gigioSouza/consolidAcao/tree/snapshot/tabbing-behavior)

Install front-end dependencies with `npm install` and run the following commands in different terminal windows:
```
// runs the fron-end devServer
npm run dev

// runs the tauri app in dev mode
npm run tauri:dev
```

Follow this gif to setup the first steps which you'll just need to select a directory where you want the app to store your data, like sqlite database.
It will create a directory called `consolidAcao` in the directory you choose.
You may skip this step, first skip the gif.
tauri-tabindex-4

To skip the apps first steps, open the devtools in the console tab and run the following command in it:
```js
location.href = 'http://localhost:8080/home'
```

You'll be redirected to the following page
image

Now you'll only need to press the TAB button from your keyboard and check that the input radio, input checkbox and button will never get focused.
(I added a CSS to outline in red the focused element).

> All elements in this sample are using the atribute `tabindex` with a number greater than `0`

**Expected behavior**
Be able to interact with any form control using TAB navigation.

**Screenshots**
Tabbing in Tauri instance
tauri-tabindex-1

Tabbing in Brave Browser
tauri-tabindex-2

Tabbing in Safari, after [allowing tab navigation through System Preferences](https://stackoverflow.com/questions/1848390/safari-ignoring-tabindex)
tauri-tabindex-3

**Platform and Versions (please complete the following information):**
OS: Mac OS, version 11.5.0 X64
Rustc: 1.54.0
Node: v16.6.1

**Would you assign yourself to resolve this bug?**
- [ ] Yes
- [x] No

**Additional context**
None

### PR DESCRIPTION
**Pull request by FabianLars**
I forgot the changefile as always, but i'll add it once i'm back and if someone can confirm that this actually works (it did work in my mac vm).

Furthermore we might want to solve this differently, like giving the user an option to choose if this should be enabled or not, because apparently the default shortcut for this is command+tab instead of tab :shrug: (i'd prefer to force this behavior for cross-platform consistency)

### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [ ] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

File: src/webview/wkwebview/mod.rs [hunk 1]
```diff
@@ -261,6 +261,9 @@ impl InnerWebView {
         let _: id = msg_send![_preference, setValue:_yes forKey:dev];
       }
 
+      #[cfg(target_os("macos"))]
+      let _: () = msg_send![_preference, setValue:_yes forKey:NSString::new("tabFocusesLinks")];
```
Comment (FabianLars) [inline src/webview/wkwebview/mod.rs]: should this be `let _: id = `?

Comment (wusyong) [reply src/webview/wkwebview/mod.rs]: You are right with this one. But the syntax of cfg should be `#[cfg(target_os = "macos")]`

Comment (FabianLars) [reply src/webview/wkwebview/mod.rs]: Ah whoops, you're right

**Comment by wusyong** [comment]
Just runned some website login pages and it seems working

**Review by wusyong — APPROVED** [review]
