### PR TITLE
Disable WebView2 mini menu ("OOUI") (fix #535)

### LINKED ISSUE #535: [bug] The mini menu of windows webview still exists in production mode
### Describe the bug

image

If some text selected, the windows webview (edge) will show a mini menu like the image shows. This is not too important in development mode, but in production mode this could lead to some potential bugs that could compromise the app. Webview2 seems to have related commands that can be prohibited, but no configuration is displayed in tauri.

Relative issue:
https://github.com/MicrosoftEdge/WebView2Feedback/issues/2140
https://github.com/wailsapp/wails/issues/1188

### Reproduction

build a windows app

### Expected behavior

_No response_

### Platform and versions

```shell
Operating System - Windows, version 10.0.19044 X64
Webview2 - 99.0.1150.55
Visual Studio Build Tools:
   - Visual Studio Community 2019

Node.js environment
  Node.js - 14.17.6
  @tauri-apps/cli - 1.0.0-rc.5 (outdated, latest: 1.0.0-rc.8)
  @tauri-apps/api - Not installed

Global packages
  npm - 6.14.11
  pnpm - 6.23.6
  yarn - 1.22.17

Rust environment
  rustup - 1.24.3
  rustc - 1.59.0
  cargo - 1.59.0
  toolchain - stable-x86_64-pc-windows-msvc 

App directory structure
/.git
/.parcel-cache
/client
/dist
/node_modules
/server

App
  tauri - 1.0.0-rc.6
  tauri-build - 1.0.0-rc.5
  tao - 0.7.0
  wry - 0.14.0
  build-type - bundle
  CSP - default-src 'self'
  distDir - ../dist
  devPath - http://localhost:3000/
  framework - React
```

### Stack trace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by JensMertelmeyer**
### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Other information
This disables the "mini menu" referenced in #535 by using the `AdditionalBrowserArguments` when creating the WebView2 environment. 

Previously, `CreateCoreWebView2EnvironmentWithOptions(..)` was only called when `data_directory` in `WebContext` was set, otherwise just `CreateCoreWebView2Environment(..)`. I have changed it a bit to always call it "with options", and passing `PWSTR::default()` as a data directory if none was given. 

Existing behaviour has not been changed, just the "mini menu" has been disabled.

### CODE REVIEW

File: src/webview/webview2/mod.rs [hunk 1]
```diff
@@ -94,26 +94,30 @@ impl InnerWebView {
...
-          .map_err(webview2_com::Error::WindowsError);
-          let _ = take_pwstr(data_directory);
-
-          return result;
-        }
-
-        CreateCoreWebView2Environment(environmentcreatedhandler)
-          .map_err(webview2_com::Error::WindowsError)
+        let options: ICoreWebView2EnvironmentOptions;
+        options = CoreWebView2EnvironmentOptions::default().into();
```
Comment (amrbashir) [inline src/webview/webview2/mod.rs]:
```suggestion
        let options: ICoreWebView2EnvironmentOptions = CoreWebView2EnvironmentOptions::default().into();
```

File: src/webview/webview2/mod.rs [hunk 2]
```diff
@@ -94,26 +94,30 @@ impl InnerWebView {
...
+        // remove "mini menu" - See https://github.com/tauri-apps/wry/issues/535
+        let additional_arguments = pwstr_from_str("--disable-features=msWebOOUI,msPdfOOUI");
+        let _ = options.SetAdditionalBrowserArguments(additional_arguments);
+        
+        // if data_directory is None, we set it to a null PWSTR 
+        let data_directory: PWSTR =
+          match data_directory {
+            Some(s) => pwstr_from_str(&s),
+            None => PWSTR::default(),
+          };
```
Comment (amrbashir) [inline src/webview/webview2/mod.rs]:
```suggestion
        let data_directory: PWSTR = data_directory.map(|s| pwstr_from_str(&s)).unwrap_or_default();
```

**Review by amrbashir — CHANGES_REQUESTED** [review]
Thanks for taking time to implement this.

**Review by amrbashir — DISMISSED** [review]
LGTM! and It works fine.

**Comment by wusyong** [comment]
Could you run `cargo fmt`? I'll merge once it's passed formatting CI
