### PR TITLE
On macOS, pass key event to menu on key press

### LINKED ISSUE #2626: MacOS: Keypress on non-input element triggers unsupported key feedback sound.
### **Describe the bug**
When a keypress event occurs on a non-content editable DOM element, the unsupported key feedback sound.

### **To Reproduce**
1. Launch a Tauri window with a Webview that contains no content-editable DOM elements (i.e. no input).
2. Click the window to bring it into focus.
3. Press any key on your keyboard
4. You should hear a light beeping sound with each keystroke.

### **Expected behavior**
No unsupported key feedback sound effect should play.

### **Screenshots**
Not really applicable

### **Platform and Versions (required):**
```
Operating System - Mac OS, version 11.5.2 X64

Node.js environment
  Node.js - 16.0.0
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 7.10.0
  yarn - 1.22.10

Rust environment
  rustc - 1.51.0
  cargo - 1.51.0

App directory structure
/dist
/node_modules
/src-tauri
/src

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../dist
  devPath - http://localhost:9000
  framework - React
  bundler - Webpack
```

### **Additional context**
The error can be stopped with e.preventDefault(), but this will block input interaction.

Tauri Conf:
```
{
  "package": {
    "productName": "complex",
    "version": "0.1.0"
  },
  "build": {
    "distDir": "../dist",
    "devPath": "http://localhost:9000",
    "beforeDevCommand": "",
    "beforeBuildCommand": ""
  },
  "tauri": {
    "bundle": {
      "active": true,
      "targets": "all",
      "identifier": "com.tauri.dev",
      "icon": [
        "icons/32x32.png",
        "icons/128x128.png",
        "icons/128x128@2x.png",
        "icons/icon.icns",
        "icons/icon.ico"
      ],
      "resources": [],
      "externalBin": [],
      "copyright": "",
      "category": "DeveloperTool",
      "shortDescription": "",
      "longDescription": "",
      "deb": {
        "depends": [],
        "useBootstrapper": false
      },
      "macOS": {
        "frameworks": [],
        "minimumSystemVersion": "",
        "useBootstrapper": false,
        "exceptionDomain": "localhost",
        "signingIdentity": null,
        "entitlements": null
      },
      "windows": {
        "certificateThumbprint": null,
        "digestAlgorithm": "sha256",
        "timestampUrl": ""
      }
    },
    "updater": {
      "active": false
    },
    "allowlist": {
      "all": true
    },
    "windows": [
      {
        "title": "Complex",
        "width": 316,
        "height": 600,
        "resizable": false,
        "fullscreen": false,
        "transparent": false,
        "decorations": true
      }
    ],
    "security": {
      "csp": "default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'"
    }
  }
}
```

### **Stack Trace**
Not applicable.

### PR DESCRIPTION
**Pull request by wusyong**
### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/wry/blob/dev/.changes/readme.md).
- [x] I have added a convincing reason for adding this feature, if necessary

### Other information
fix https://github.com/tauri-apps/tauri/issues/2626

### CODE REVIEW

**Review by amrbashir — APPROVED** [review]

File: src/webview/wkwebview/mod.rs [hunk 1]
```diff
@@ -287,6 +295,20 @@ impl InnerWebView {
...
+              unsafe {
+                let app = cocoa::appkit::NSApp();
+                let menu: id = msg_send![app, mainMenu];
+                if !menu.is_null() {
+                  let () = msg_send![menu, performKeyEquivalent: event];
+                }
+              }
+            }
+            // We need to declare this method to get Command+ key equivalent.
+            extern "C" fn do_command_by_selector(_: &Object, _: Sel, _: Sel) {}
```
Comment (amrbashir) [inline src/webview/wkwebview/mod.rs:311]: can this fix be upstream to `winit`? seems like a valid use-case for any winit app.

Comment (wusyong) [reply src/webview/wkwebview/mod.rs:311]: winit can call `performKeyEquivalent` in `WinitWindow`'s `sendEvent` but I'm not sure if winit team willing to take this workaround. Key event chain in macOS is a mess tbh.

As for workaround for users of winit, I think we can add a NSView as subview and add similar code like above. Or just replace `winitWindow` with default NSView if they don't care any window events sent from winit like we did before (we can't do this in wry anymore since event like resize has moved to winitView).

Comment (amrbashir) [reply src/webview/wkwebview/mod.rs:311]: winit ships with a default menu so this workaround is valid for their use-case too but we won't know for sure until we open a PR.
